### ISSUE TITLE
build an example for audio data

### ISSUE THREAD

**Issue by nan-wang** [jina-ai/examples#191]

**Comment by jyothishkjames** [comment]
Hi,

I am trying to use the AudioReader executor to load audio data, but fails with the following errors from the logs.

![Screenshot from 2020-09-21 11-26-37](https://user-images.githubusercontent.com/937528/93752183-91868a80-fbfe-11ea-8bfa-c3959712c8ba.png)

craft-load.yml
------------------

!AudioReader
with:
  sample_rate: 22050
metas:
  name: reader
requests:
  on:
    IndexRequest:
      - !CraftDriver
        with:
          executor: reader
    SearchRequest:
      - !CraftDriver
        with:
          executor: reader
    ControRequest:
      - !ControlReqDriver {}

**Comment by JoanFM** [comment]
Hello @jyothishkjames , can you provide more details how are u using it?

It seems that the `uri` that the crafter is receiving is invalid

**Comment by jyothishkjames** [comment]
Hello @JoanFM,

I have the .wav files in a folder, and the path to the folder is given as a pattern as below.
if task == 'index':
    f = Flow().load_config('flow-index.yml')
    with f:
        f.index_files(**f'{data_path}/*.wav'**, size=num_docs, read_mode='rb', batch_size=2)

**Comment by JoanFM** [comment]
Can u have this:

```yaml
!AudioReader
with:
sample_rate: 22050
metas:
name: reader
requests:
on:
IndexRequest:
- !LogInfoDriver {}
- !CraftDriver
with:
executor: reader
SearchRequest:
- !LogInfoDriver {}
- !CraftDriver
with:
executor: reader
ControRequest:
- !ControlReqDriver {}
```

this should print the messages that go to the flow right before the crafter. You should see if the document received a valid `uri` value.
