### ISSUE TITLE
Southpark indexing terminated

### ISSUE THREAD

**Issue by aoleiReiz** [jina-ai/examples#248]
callback() may not work properly due to the bad response: chunk_indexer(CompoundIndexer) throws AttributeError("'NoneType' object has no attribute 'write'")
/jina/executors/indexers/vector.py\", line 116, in add\n    self.write_handler.write(vectors.tobytes())\nAttributeError: \'NoneType\' object has no attribute \'write\'\n"

jina               0.6.5
when i using jina lower version, it turned out missing some jina package.

**Comment by JoanFM** [comment]
Hello @aoleiReiz,

Thank you very much for your feedback!

Could you please provide a detailed description of your problem? 

What version of jina are you running? What steps did you run?

And when dealing with an error? Could you provide some detailed logs for us to be able to better find the root cause of the problem?

Thank you very much

**Comment by aoleiReiz** [comment]
when do the indexing, the hander object turn to be nonetype sometime, when do the query, no result printed

**Query**
search [=                   ] 📃    100 ⏱️ 0.3s 🐎 384.9/s      1      batch        gateway@6775[I]:#sent: 1 #recv: 1 sent_size: 354 Bytes recv_size: 466 Bytes
    0 seconds (0.27s)
        ✅ done in ⏱ 0 seconds 🐎 372.6/s
        gateway@6775[S]:terminated

**Indexing**
executors/indexers/vector.py", line 116, in add
    self.write_handler.write(vectors.tobytes())
AttributeError: 'NoneType' object has no attribute 'write'

    @cached_property
    def write_handler(self):
        """A writable and indexable object, could be dict, map, list, numpy array etc.

        .. note::
            :attr:`query_handler` and :attr:`write_handler` are by default mutex
        """

        # ! a || ( a && b )
        # =
        # ! a || b
        print("*********")
        if not self.handler_mutex or not self.is_handler_loaded:
            r = self.get_add_handler() if self.is_exist else self.get_create_handler()
            if r is None:
                self.logger.warning('"write_handler" is None, you may not add data to this index, '
                                    'unless "write_handler" is later assigned with a meaningful value')
            else:
                self.is_handler_loaded = True
            return r

blis               0.4.1     
catalogue          1.0.0     
certifi            2020.6.20 
chardet            3.0.4     
click              7.1.2     
cymem              2.0.3     
en-core-web-lg     2.3.1     
filelock           3.0.12    
Flask              1.1.2     
Flask-Cors         3.0.9     
fluent-logger      0.9.6     
gevent             20.9.0    
greenlet           0.4.17    
grpcio             1.32.0    
idna               2.10      
importlib-metadata 2.0.0     
itsdangerous       1.1.0     
jina               0.6.5     
Jinja2             2.11.2    
joblib             0.17.0    
lz4                3.1.0     
MarkupSafe         1.1.1     
msgpack            0.6.2     
murmurhash         1.0.2     
numpy              1.19.2    
packaging          20.4      
pip                19.0.3    
plac               1.1.3     
preshed            3.0.2     
protobuf           3.13.0    
pyparsing          2.4.7     
python-magic       0.4.18    
pyzmq              19.0.2    
regex              2020.10.11
requests           2.24.0    
ruamel.yaml        0.16.12   
ruamel.yaml.clib   0.2.2     
sacremoses         0.0.43    
scipy              1.5.2     
sentencepiece      0.1.91    
setuptools         40.8.0    
six                1.15.0

**Comment by JoanFM** [comment]
Hello @aoleiReiz ,

Can you make sure that the workspace is removed before reindexing?

**Comment by aoleiReiz** [comment]
My mistake, remove the workspace, it worked. but query doesn't get any result

**Comment by JoanFM** [comment]
> My mistake, remove the workspace, it worked. but query doesn't get any result

It is weird, because for me it works, 

What are the exact steps you follow?

**Comment by aoleiReiz** [comment]
here is the different codes, others are same with the repo
**Flow-query**
`!Flow
with:
  read_only: true
  port_expose: $JINA_PORT
pods:
  encoder:
    uses: pods/encoder/spacy_encoder.yml
    timeout_ready: 60000
    read_only: true
  chunk_indexer:
    uses: pods/index-chunk.yml
    polling: all
    uses_reducing: _merge_all
  doc_indexer:
    uses: pods/index-doc.yml`

**spacy encoder**
`class SpacyEncoder(BaseEncoder):

    def __init__(self, greetings: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._greetings = greetings

    def encode(self, data: Any, *args, **kwargs):
        self.logger.info('%s %s' % (self._greetings, data[0]))
        vectors = []
        for doc in data:
            sents = str(doc).split("[INFO_SEP]")
            vector = np.array([ nlp(sent).vector for sent in sents])
            vector = np.mean(vector, axis=0)
            vectors.append(vector)
        return np.array(vectors)`
**spacy yml**
`!SpacyEncoder
with:
  greetings: spacy encoder
metas:
  name: spacy-encoder
  py_modules: spacy_encoder.py
  workspace: pods/encoder`

**Comment by JoanFM** [comment]
Hello @aoleiReiz,

Firs of all, are you using different encoders for `indexing` and `querying`? This can be a source of problems, because one can't guarantee that the embeddings of query and index time hold the same meaning.

Also, if the embeddings resulting at index and query time are not of the same length, the Flow will not be able to retrieve matches

**Comment by aoleiReiz** [comment]
i'm using same encoder  for indexing and querying, the vector length are all 300, thanks for your advise, let me check my code in detail, if any problem, will come back to you. thanks for your help

**Comment by JoanFM** [comment]
> i'm using same encoder for indexing and querying, the vector length are all 300, thanks for your advise, let me check my code in detail, if any problem, will come back to you. thanks for your help

Well, in your changes it seemed that you were only changing `Flow-query` but not `Flow-index` and that's why I was asking

**Comment by aoleiReiz** [comment]
**Flow index**, the encoder will generate ndarray for (data.shape[0], 300), i follow this tutorial changed the encoder work https://docs.jina.ai/chapters/extend/mwu.html
!Flow
pods:
  extractor:
    uses: pods/extract.yml
  encoder:
    uses: pods/encoder/spacy_encoder.yml
    timeout_ready: 1200000
    read_only: true
  chunk_indexer:
    uses: pods/index-chunk.yml
  doc_indexer:
    uses: pods/index-doc.yml
    needs: extractor
  join_all:
    uses: _merge
    needs: [doc_indexer, chunk_indexer]
    read_only: true

**Comment by JoanFM** [comment]
Can you please send the 4 files: 

`flow-index.yml`,  `flow-query.yml`, `pods/encoder/spacy_encoder.yml` and the `spacy_encoder.py`?

**Comment by aoleiReiz** [comment]
**Flow-index.yml**
```
!Flow
pods:
  extractor:
    uses: pods/extract.yml
  encoder:
    uses: pods/encoder/spacy_encoder.yml
    timeout_ready: 1200000
    read_only: true
  chunk_indexer:
    uses: pods/index-chunk.yml
  doc_indexer:
    uses: pods/index-doc.yml
    needs: extractor
  join_all:
    uses: _merge
    needs: [doc_indexer, chunk_indexer]
    read_only: true
```
**Flow-query.yml**
```
!Flow
with:
  read_only: true
  port_expose: $JINA_PORT
pods:
  encoder:
    uses: pods/encoder/spacy_encoder.yml
    timeout_ready: 60000
    read_only: true
  chunk_indexer:
    uses: pods/index-chunk.yml
    polling: all
    uses_reducing: _merge_all
  doc_indexer:
    uses: pods/index-doc.yml
```
**pods/encoder/spacy_encoder.yml**
```
!SpacyEncoder
with:
  greetings: spacy encoder
metas:
  name: spacy-encoder
  py_modules: spacy_encoder.py
  workspace: pods/encoder
```
**spacy_encoder.py**
```
from typing import Any

import numpy as np
import spacy

from jina.executors.encoders import BaseEncoder


nlp = spacy.load("en_core_web_lg")


class SpacyEncoder(BaseEncoder):

    def __init__(self, greetings: str, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._greetings = greetings

    def encode(self, data: Any, *args, **kwargs):
        self.logger.info('%s %s' % (self._greetings, data[0]))
        vectors = []
        for doc in data:
            sents = str(doc).split("[INFO_SEP]")
            vector = np.array([ nlp(sent).vector for sent in sents])
            vector = np.mean(vector, axis=0)
            vectors.append(vector)
        return np.array(vectors)

```

**Comment by JoanFM** [comment]
Can you send the logs resulting from `index` run?

**Comment by JoanFM** [comment]
And can you provide the details on to what needs to be done to hae the model `en_core_web_lg` in a local machine?

**Comment by JoanFM** [comment]
And there is something even more strange, in the example code, there is only one index pod yaml description but your code expects 2 (index-chunk.yml and index-doc.yml): So either you have more changes to it or there is some mix or missunderstanding between versions of the code maybe?

So having the same spacy_encoder but changing Flows  to the following works for me:

flow-index.yml
```
!Flow
pods:
  extractor:
    uses: pods/extract.yml
  encoder:
    uses: pods/encoder/spacy_encoder.yml
    timeout_ready: 1200000
    read_only: true
  indexer:
    uses: pods/index.yml
```

flow-query.yml
```
!Flow
with:
  read_only: true
  port_expose: $JINA_PORT
pods:
  encoder:
    uses: pods/encoder/spacy_encoder.yml
    timeout_ready: 60000
    read_only: true
  indexer:
    uses: pods/index.yml
    polling: all
    uses_reducing: _merge_all
```

I hope you find this helpful!! I have done just the assessment that query results are obtained but did not check their quality
