### ISSUE TITLE
FAISS example is broken

### ISSUE THREAD

**Issue by janandreschweiger** [jina-ai/examples#316]
Neither the flow-query.yml nor the yaml/indexer.yml use the faiss-indexer. Actually the yaml/query-indexer.yml and the yaml/faiss are never used.

Moreover, could someone please take a closer look on this example. I think the whole example should be updated to the latest version. For example the yaml/query-indexer.yml uses outdated arguments (traverse_on, depth_range) that can not be found in the latest documentation.

I appreciate any help :)

**Comment by janandreschweiger** [comment]
As we use FAISS to search sentence embeddings we use the plain IndexFlatL2 index (no downprojection, no training data).
Do you know if FAISS is still faster than jina.ai out of the box for querying?

**Comment by alexcg1** [comment]
Hey there!

Alex here from Jina's dev rel team. Thanks for getting in touch - we've been snowed under lately but we've allocated time in January to go through and rework plenty of our examples.

Hope you can hang on and bear with us til then, and sorry for the trouble!

Cheers,
Alex

**Comment by cristianmtr** [comment]
Hey @janandreschweiger 

I just ran this successfully on Python 3.7 using the instruction from the README, on a clean virtualenv. What is the problem you are facing exactly?

**Comment by janandreschweiger** [comment]
Hi @cristianmtr! Thank you for your comment!

Please take a look at the indexer in the flow-query.yml file. Instead of using the yaml/query-indexer.yml it uses the yaml/indexer.yml!

So it works for you, because this example doesn't actually use the faiss-indexer for querying. It uses the plain NumpyIndexer again that should only be used for indexing the documents.

**Comment by JoanFM** [comment]
Hey @janandreschweiger ,

You are right, we did not realise it was broken, I would like to let you know that we identified the issue, and here there is a PR to try to update the example to use FAISS properly but it is waiting for some other issues to be fixed. 

https://github.com/jina-ai/examples/pull/318

It will not be usable for now (an issue in core has been opened), and we may need to have some work to make it easier to use. But it can serve to you as an indication on how it should be used.

**Comment by janandreschweiger** [comment]
Cool @JoanFM. That would be nice. I had a look at your branch https://github.com/jina-ai/examples/tree/adapt-faiss-search.

I don't see any reason to use docker for faiss. So I would prefer to run the pod locally. Nevertheless, I tried both options (local & within a docker image)

**Local**
Using faiss without docker leads to the following output:
```
chunk_idx@196068[I]:recv SearchRequest from gateway▸encoder▸chunk_idx▸⚐
chunk_idx@196068[S]:memmap is enabled for ./workspace/vec.gz
chunk_idx@196068[I]:loading index from None...
chunk_idx@196068[E]:TypeError('filename must be a str or bytes object, or a file')
```
The _load_gzip method in https://docs.jina.ai/_modules/jina/executors/indexers/vector.html raises this error at line 142, because self.index_abspath is None. But as you can see I defined the filename in the Indexer:

This is my pods/chunk.yml:
```
!CompoundIndexer
components:
  - !FaissIndexer
    with:
      index_key: IVF4096,Flat
      index_filename: vec.gz  # DEFINED HERE
      ref_indexer:
        !NumpyIndexer
        metas:
          workspace: $WORKSPACE
          name: vec_idx
        with:
          index_filename: vec.gz  # AND HERE
    metas:
      workspace: $WORKSPACE
      name: faiss_idx
  - !BinaryPbIndexer
    with:
      index_filename: chunk.gz
    metas:
      name: chunk_idx
      workspace: $WORKSPACE
metas:
  name: chunk_compound_idx
  workspace: $WORKSPACE
requests:
  on:
    SearchRequest:
      - !VectorSearchDriver
        with:
          executor: faiss_idx
      - !KVSearchDriver
        with:
          executor: chunk_idx
          traversal_paths: ['m']
```

My query flow looks like this:
```
!Flow
pods:
... # other pods
  chunk_idx:
    uses: pods/chunk.yml
    timeout_ready: 600000
... # other pods
```

**Docker**
When using the docker image I get this error:
```
unknown exception: ModuleNotFoundError("No module named 'docker'")
```
I don't know why I get this error. I use python 3.8 and I have installed the python docker package. I can even import it in the python shell.

My team and I really appreciates your support. Thank you!
