### ISSUE TITLE
some questions about callback functino by the webqa-search example  in latest version 0.8.2

### ISSUE THREAD

**Issue by ultimatedaotu** [jina-ai/examples#319]
1. I wonder how does this function of `print_topK()`  work. My understanding is that it works after the last pod, while the last pod is chunk_indexer, it works well and return mathching chunks. But while two pods of ranker and doc_indexer are added, I can not get the real docs as supposed. I want to retrieve additional information(such as time clips and movie ids) about the caption by retrieving the caption text field. Each document is a string of json format.
2. The format of the response is obtained by printing the return information at the end of chunk_indexer. At the end of doc_indexer, **the response is NILL,** so how could I get the real response? It seems that I can't  find any documentation instructions of the response。
3. After starting the service, should I use the tool of curl or restful api to get the results instead of the console? 
4. Index created successfully with no other errors reported

**Comment by cristianmtr** [comment]
It should work after 

```
  join:
    uses: _merge
    needs: [chunk_indexer, doc_indexer]
    read_only: True
```

So the data should be there. Have you tried debugging and inspecting the `resp` object? 

I will have a look now

**Comment by ultimatedaotu** [comment]
the version of transformers  is 4.0.0, I have modified the encoder and extractor to meet my task, the index flow works well, but there is a problem with the full workflow.

extractor:
```python
import json
from jina.executors.crafters import BaseSegmenter


class SubtitleExtractor(BaseSegmenter):

    def is_chinese(self, sent):
        sent_new = ''
        for uchar in str(sent):
            if uchar >= u'\u4e00' and uchar <= u'\u9fa5':
                sent_new += uchar
            else:
                continue
        return sent_new

    def craft(self, text, *args, **kwargs):
        json_dict = json.loads(text)
        content = json_dict['content']
        content = content.strip()
        content = self.is_chinese(content)
        print("content:====", content)

        return [dict(text=content)]

```

```
when the query-flow is:
!Flow
pods:
  extractor:
    uses: pods/extractor/extractor.yml
    read_only: True

  encoder:
    uses: pods/encoder/encoder.yml
    timeout_ready: 60000
    read_only: True

  chunk_indexer:
    uses: pods/chunk_indexer/chunk_indexer.yml
    timeout_ready: 600000
    read_only: True
```

print the **resp.search.docs**

```
  return torch._C._cuda_getDeviceCount() > 0
  chunk_indexer@24303[I]:recv SearchRequest from gateway▸extractor▸encoder▸chunk_indexer▸⚐
  chunk_indexer@24303[S]:memmap is enabled for WORKSPACE/vecidx_index.gzip
  chunk_indexer@24303[I]:indexer size: 200
  chunk_indexer@24303[I]:indexer size: 200
以下是相似的问题:
resp: <jina.types.request.Request object at 0x7fd330347550>
resp.search.docs: [id: "55a543d491e66b7a"
weight: 1.0
length: 100
matches {
  id: "35d7f45ad2277352"
  weight: 1.0
  length: 10
  mime_type: "text/plain"
  text: "\345\270\270\345\270\270\345\274\204\351\224\231"
  embedding {
    dense {
      buffer: "\023\217,?\263+\036?\214\010n?\020|H\276\315%\021\277\r\320\337\2767:\000?\267`\212>\035\271Z>\3211b=\230N\215\274\017)\315\274T<{\277\343\331\310>\323?L\276\177\313\332?\255\273\n?\240\344\024?ne\207\276\230\276\246\277\017\221Q?\326\307\030?\205\005\213\277\274\371\001\275B\310\364>$j&\276\310\005-\277\026x4\276\230\246K?A\312\003=\013)
......
```

----------------

when the query-flow is:
```
!Flow
pods:
  extractor:
    uses: pods/extractor/extractor.yml
    read_only: True

  encoder:
    uses: pods/encoder/encoder.yml
    timeout_ready: 60000
    read_only: True

  chunk_indexer:
    uses: pods/chunk_indexer/chunk_indexer.yml
    timeout_ready: 600000
    read_only: True

  ranker:
    uses: pods/ranker/ranker.yml
    read_only: True

  doc_indexer:
    uses: pods/doc_indexer/doc_indexer.yml
    read_only: True
```

the resp object return **null**
  ```
chunk_indexer@24456[I]:recv SearchRequest from gateway▸extractor▸encoder▸chunk_indexer▸⚐
  chunk_indexer@24456[S]:memmap is enabled for WORKSPACE/vecidx_index.gzip
  chunk_indexer@24456[I]:indexer size: 200
  chunk_indexer@24456[I]:indexer size: 200
         ranker@24463[I]:recv SearchRequest from gateway▸extractor▸encoder▸chunk_indexer▸ranker▸⚐
    doc_indexer@24468[I]:recv SearchRequest from gateway▸extractor▸encoder▸chunk_indexer▸ranker▸doc_indexer▸⚐
    doc_indexer@24468[I]:indexer size: 0
以下是相似的问题:
**resp: <jina.types.request.Request object at 0x7f93e27d3100>
resp.search.docs: []**
search [=                   ] 📃    100 ⏱️ 6.9s 🐎 14.5/s      1      batch        gateway@24433[I]:#sent: 1 #recv: 1 sent_size: 593 Bytes recv_size: 845 Bytes
    6 seconds (6.90s)
        ✅ done in ⏱ 6 seconds 🐎 14.5/s
       PyClient@24433[S]:terminated
请输入问题: 
```

is the object of resp the same in both above processes？ What kind of resp it returns after the chunk_indexer? How can I get it at console or by other api tool?
